# Generated by Django 4.2.7 on 2023-11-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('event_name', models.CharField(max_length=60)),
                ('event_url', models.URLField()),
                ('image_url', models.URLField()),
                ('event_date', models.CharField(max_length=60)),
                ('event_time', models.CharField(max_length=20)),
                ('event_venue', models.CharField(max_length=60)),
                ('event_address', models.CharField(max_length=60)),
                ('event_state', models.CharField(max_length=60)),
                ('event_city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
