# Generated by Django 4.2.7 on 2023-12-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventSpotter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=60)),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
